### ISSUE TITLE
Custom GraphQLError

### ISSUE THREAD

**Issue by gforge** [joonhocho/graphql-input-string#2]
I would like to return an error without the input value but I can't figure out how to add the error option, so far I've tried versions of:

```
const GraphQLPassword = GraphQLInputString({
  name: 'Password',
  min: 6,
  max: 300,
  error() {
    throw GraphQLError('Invalid password - must be at least 6 characters');
  },
});

```

But I keep getting: `Variable "$password" got invalid value "tes".\nExpected type "Password", found "tes"`

Could you try improve the docs/add a test or example?

Thanks for the help and this neat package!

**Comment by joonhocho** [comment]
@gforge can you log inside your error function? 
```javascript
error() {
console.log('error args', arguments);
throw ...
}
```
like this and see what it prints?
The code is pretty simple and straight forward and if you want to see examples then you can look at the test code. There are plenty of test cases testing each parameter.
If you want to dig dipper then you can also take a look at source code which is very simple as well!

**Comment by gforge** [comment]
Here's the output:

```
  error args { '0': 
   { type: 'min',
     value: '"#!',
     min: 6,
     message: 'Expected minimum length "6"',
     ast: undefined } }

  0 passing (197ms)
  1 failing

  1) Create tests: Don't leak password when wrong GraphQL type:
     AssertionError: expected 'Variable "$password" got invalid value "\\"#!".\nExpected type "Password", found "\\"#!": Object.defineProperty called on non-object' not to match /"#!/
      at _callee$ (src/schema/user/tests/create.spec.js:41:42)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:64:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:299:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:116:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

The test-case that I use:

```js
  it.only('Don\'t leak password when wrong GraphQL type', async () => {
    // TODO: issue started: https://github.com/joonhocho/graphql-input-string/issues/2
    const mutation = `
    mutation signup($username: Username!, $password: Password!) {
      user{
        signup(username: $username, password: $password) {
          id
        }
      }
    }`;
    const postData = {
      query: mutation,
      variables: {
        username: 'other',
        password: '"#!',
      },
    };

    const res = await agent
    .post('/graphql')
    .send(postData)
    .then(parseRetData)
    .catch(err => expect(err).to.not.exist);

    expect(res.errors).to.exist;
    expect(res.errors[0].message).to.not.match(/"#!/);
  });
```

**Comment by joonhocho** [comment]
@gforge yeah I think you made a mistake.
it should be `throw new GraphQLError...` not `throw GraphQLError...`.

**Comment by gforge** [comment]
Thanks. That solved the Object error, the problem that I would like to solve is though the fact that the error message leaks back the password. With the `new` the error message is correct but graphql still adds the password: 

```
AssertionError: expected 'Variable "$password" got invalid value "\\"#!".\nExpected type "Password", found "\\"#!": Invalid password - has to be between 6 & 300 characters' not to match /"#!/
```

I guess this is too much to ask of the system and something that probably should be solved at the front-end and not the back-end.

Btw: I think it would be nice with an automated descriptor property if none has been added, what do you think? E.g. if there is no descriptor in the config you could autogenerate one depending on the min/max & pattern. If there are more custom arguments the descriptor could be more general with an encouragement for adding a custom descriptor.

Again, thanks for the help and this neat package.

**Comment by joonhocho** [comment]
@gforge Yes, you are correct. There is nothing this library can do about graphql printing the original value, but if you take a look at libraries like `express-graphql`, then you can supply an option value that formats error message on server application layer.

**Comment by joonhocho** [comment]
I don't know what you mean by descriptor property.
